name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  flutter_slidable: ^3.1.1
  flutter_colorpicker: ^1.1.0
  country_code_picker: ^3.0.0
  yuno:
   path: ../
  # firebase_core: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
